# --- Model Parameters (with rationale comments) ---
# Based on biological plausibility, relative timescales, and model tuning.
# NOTE: These are illustrative estimates, not precise experimental values.
parameters = {
    # Chronic Stimulus & Basal
    'k_chronic_stimulus': 0.95, # Represents persistent underlying trigger (microbial, genetic etc.). Value set high relative to LL37 decay to maintain high chronic LL37 levels (~1.2).
    'basal_LL37': 0.01,         # Represents low-level constitutive production. Assumed small compared to chronic stimulus in disease state.

    # Decay Rates (1/day) - Inverse related to half-life (t_1/2 = ln(2)/decay_rate)
    'd_LL37': 0.8,              # Assumes LL37 peptide half-life is moderate (~21 hrs).
    'd_ProInflamm': 2.5,        # Assumes rapid turnover for pro-inflammatory cytokines (~7 hr half-life).
    'd_NLRP3': 1.5,             # Represents moderate deactivation/turnover rate of the active inflammasome complex (~11 hr half-life).
    'd_VEGF': 0.6,              # Assumes VEGF has a longer half-life than inflammatory cytokines (~28 hrs).
    'd_Erythema': 0.07,         # Represents very slow clinical resolution of redness (t_1/2 ~10 days), ensuring persistence.
    'd_IL10_tissue': 2.5,       # Assumes rapid clearance/decay for IL-10 molecule in tissue (~7 hr half-life).
    'd_IL10_Effect': 0.7,       # Decay rate for the downstream effect (t_1/2 ~ 1 day), slower than IL-10 molecule but faster than initial guess.

    # Production/Activation Rates (Relative values tuned for plausible steady state)
    'k_LL37_inflamm': 1.0,      # Rate ProInflamm production is driven by LL37.
    'k_nlrp3_inflamm': 0.8,     # Rate ProInflamm production is driven by NLRP3.
    'k_LL37_nlrp3': 0.5,        # Rate LL37 activates NLRP3.
    'k_LL37_vegf': 0.2,         # Rate VEGF production is driven by LL37.
    'k_inflamm_vegf': 0.4,      # Rate VEGF production is driven by ProInflamm cytokines.
    'k_vegf_eryth': 0.15,       # Rate Erythema score increases due to VEGF.
    'k_inflamm_eryth': 0.15,    # Rate Erythema score increases due to ProInflamm cytokines.
    'k_produce_IL10_effect': 1.0, # Rate the downstream effect is generated by IL10_tissue.

    # Patch Release & Degradation (1/day)
    'k_release_IL10': 0.4,      # Release rate from patch (first-order simplification, t_1/2 ~1.7 days). Represents multi-day release goal.
    'k_degrade_patch_IL10': 0.05,# Estimated degradation rate of IL-10 within hydrogel (t_1/2 ~14 days). Educated guess.

    # Therapeutic Effects (mediated by IL10_Effect)
    'k_il10_effect_supp_LL37': 1.8,     # Strength effect suppresses LL37. Tuned for potency.
    'k_il10_effect_supp_inflamm': 1.8,  # Strength effect suppresses ProInflamm. Tuned for potency.
}